version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: pdf-to-excel-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CLOUDCONVERT_API_KEY=${CLOUDCONVERT_API_KEY}
      - DATABASE_URL=sqlite:///data/bot.db
      - MAX_FILE_SIZE=20971520
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  bot-data:
    driver: local 